// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Supabase configuration
const SUPABASE_URL = "https://sbxvahqsaonzusgudvzt.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNieHZhaHFzYW9uenVzZ3Vkdnp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUwNzYzNDUsImV4cCI6MjA4MDY1MjM0NX0.kG4nQ0fot1jsTFjb0CAQzvdeeyo8JuJ9y6ctRnP_n6k";

const supabaseUrl =
  import.meta.env.VITE_SUPABASE_URL ||
  (window as any)?.__SUPABASE_URL__ ||
  SUPABASE_URL;

const supabaseKey =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY ||
  (window as any)?.__SUPABASE_ANON_KEY__ ||
  SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
